<?php

declare(strict_types=1);

namespace MusahMusah\LaravelMultipaymentGateways\Contracts;

use MusahMusah\LaravelMultipaymentGateways\Contracts\Flutterwave\FlutterwaveBankContract;
use MusahMusah\LaravelMultipaymentGateways\Contracts\Flutterwave\FlutterwaveChargeContract;
use MusahMusah\LaravelMultipaymentGateways\Contracts\Flutterwave\FlutterwaveOtpContract;
use MusahMusah\LaravelMultipaymentGateways\Contracts\Flutterwave\FlutterwavePaymentPlanContract;
use MusahMusah\LaravelMultipaymentGateways\Contracts\Flutterwave\FlutterwaveSettlementContract;
use MusahMusah\LaravelMultipaymentGateways\Contracts\Flutterwave\FlutterwaveSubscriptionContract;
use MusahMusah\LaravelMultipaymentGateways\Contracts\Flutterwave\FlutterwaveTransactionContract;
use MusahMusah\LaravelMultipaymentGateways\Contracts\Flutterwave\FlutterwaveTransferContract;

interface FlutterwaveContract extends FlutterwaveBankContract, FlutterwaveChargeContract, FlutterwaveOtpContract, FlutterwavePaymentPlanContract, FlutterwaveSettlementContract, FlutterwaveSubscriptionContract, FlutterwaveTransactionContract, FlutterwaveTransferContract, GatewayContract {}
