<?php

declare(strict_types=1);

namespace MusahMusah\LaravelMultipaymentGateways\Traits\Flutterwave;


trait OtpTrait
{
    /**
     * Create an OTP
     *
     * This method allows you to generate an OTP via Flutterwave for any validation.
     */
    public function createOtp(array $formParams): array
    {
        return $this->httpClient()->post(
            url: '/otps/',
            formParams: $formParams
        );
    }

    /**
     * Validate an OTP
     *
     * This method allows you to validate OTPs generated by the /create endpoint.
     */
    public function verifyOtp(string $reference, array $formParams): array
    {
        return $this->httpClient()->post(
            url: '/otps/'.$reference.'/validate',
            formParams: $formParams
        );
    }
}
