<?php

declare(strict_types=1);

namespace MusahMusah\LaravelMultipaymentGateways\Traits\Flutterwave;

use MusahMusah\LaravelMultipaymentGateways\Data\PaymentResponse;

trait OtpTrait
{
    /**
     * Create an OTP
     *
     * This method allows you to generate an OTP via Flutterwave for any validation.
     */
    public function createOtp(array $formParams): PaymentResponse
    {
        return PaymentResponse::fromArray(
            $this->httpClient()->post(
                url: '/otps/',
                data: $formParams
            )
        );
    }

    /**
     * Validate an OTP
     *
     * This method allows you to validate OTPs generated by the /create endpoint.
     */
    public function verifyOtp(string $reference, array $formParams): PaymentResponse
    {
        return PaymentResponse::fromArray(
            $this->httpClient()->post(
                url: '/otps/'.$reference.'/validate',
                data: $formParams
            )
        );
    }
}
