<?php

namespace MusahMusah\LaravelMultipaymentGateways\Traits\Flutterwave;

use MusahMusah\LaravelMultipaymentGateways\Constants\FlutterwaveConstant;

trait OtpTrait
{
    /**
     * Create an OTP
     *
     * This method allows you to generate an OTP via Flutterwave for any validation.
     */
    public function createOtp(array $formParams): array
    {
        return $this->httpClient()->post(
            url: FlutterwaveConstant::OTP_ENDPOINT,
            formParams: $formParams
        );
    }

    /**
     * Validate an OTP
     *
     * This method allows you to validate OTPs generated by the /create endpoint.
     */
    public function verifyOtp(string $reference, array $formParams): array
    {
        return $this->httpClient()->post(
            url: FlutterwaveConstant::OTP_ENDPOINT.$reference.'/validate',
            formParams: $formParams
        );
    }
}
