<?php

namespace MusahMusah\LaravelMultipaymentGateways\Traits\Flutterwave;

use GuzzleHttp\Exception\GuzzleException;
use MusahMusah\LaravelMultipaymentGateways\Constants\FlutterwaveConstant;
use MusahMusah\LaravelMultipaymentGateways\Exceptions\HttpMethodFoundException;

trait TransactionTrait
{
    /**
     * Verify a transaction.
     *
     * This endpoint helps developers to query the final status of a transaction.
     * This can be used to check transactions of all payment types after they have been attempted.
     *
     * @param  string  $transactionId The ID of the transaction to be verified.
     *
     * @throws GuzzleException|HttpMethodFoundException
     */
    public function verifyTransaction(string $transactionId): array
    {
        return flutterwave()->httpClient()->get(
            url: FlutterwaveConstant::TRANSACTION_ENDPOINT.$transactionId.'/verify'
        );
    }

    /**
     * Create a refund for a disputed transaction.
     *
     * @param  string  $transactionId The ID of the transaction to be verified.
     * @param  array  $formParams An associative array of refund data.
     *
     * @throws GuzzleException|HttpMethodFoundException
     */
    public function createTransactionRefund(string $transactionId, array $formParams = []): array
    {
        return flutterwave()->httpClient()->post(
            url: FlutterwaveConstant::TRANSACTION_ENDPOINT.$transactionId.'/refund',
            formParams: $formParams
        );
    }

    /**
     * Get multiple transactions
     *
     * @param  array  $queryParams Query parameters for filtering and pagination
     *
     * @throws GuzzleException|HttpMethodFoundException
     */
    public function getTransactions(array $queryParams = []): array
    {
        return flutterwave()->httpClient()->get(
            url: FlutterwaveConstant::TRANSACTION_ENDPOINT,
            query: $queryParams
        );
    }

    /**
     * Get multiple refund transactions
     *
     * @param  array  $queryParams Query parameters for filtering and pagination
     *
     * @throws GuzzleException|HttpMethodFoundException
     */
    public function getRefundTransactions(array $queryParams = []): array
    {
        return flutterwave()->httpClient()->get(
            url: FlutterwaveConstant::REFUND_ENDPOINT,
            query: $queryParams
        );
    }

    /**
     * Get multiple refund transactions
     *
     * @param  string  $refundId This is a unique reference for the refunded transaction
     *
     * @throws GuzzleException|HttpMethodFoundException
     */
    public function getRefundDetails(string $refundId): array
    {
        return flutterwave()->httpClient()->get(
            url: FlutterwaveConstant::REFUND_ENDPOINT.$refundId
        );
    }

    /**
     * Get the transaction fees for a particular amount and currency
     *
     * @param  array  $queryParams Query parameters for filtering
     *
     * @throws GuzzleException|HttpMethodFoundException
     */
    public function getTransactionFee(array $queryParams): array
    {
        return flutterwave()->httpClient()->get(
            url: FlutterwaveConstant::TRANSACTION_ENDPOINT.'fee',
            query: $queryParams
        );
    }

    /**
     * Resend failed webhooks to your server for a specific transaction.
     *
     * @param  string  $transactionId This is a unique reference for the refunded transaction
     * @param  array  $formParams An associative array of retry data.
     *
     * @throws GuzzleException|HttpMethodFoundException
     */
    public function resendFailedWebhook(string $transactionId, array $formParams = []): array
    {
        return flutterwave()->httpClient()->post(
            url: FlutterwaveConstant::TRANSACTION_ENDPOINT.$transactionId.'/resend-hook',
            formParams: $formParams
        );
    }

    /**
     * View transaction timeline
     *
     * @param  string  $transactionId This is a unique transaction identifier generated by our systems
     *
     * @throws GuzzleException|HttpMethodFoundException
     */
    public function viewTransactionTimeline(string $transactionId): array
    {
        return flutterwave()->httpClient()->get(
            url: FlutterwaveConstant::TRANSACTION_ENDPOINT.$transactionId.'/timeline'
        );
    }
}
